### ISSUE TITLE
How do I determine if the Hough threshold is chosen correctly?

### ISSUE THREAD

**Issue by fkcllll** [DaveHealy-Aberdeen/FracPaQ#9]
Hi All,

This program is so convenient and very helpful to me, thanks for this great tool!

I'm ashamed that I don't know much about the field of image analysis.
I felt that the User Guide was vague about determining a reasonable Hough threshold.
Could you explain it to me in detail?

Many thanks!
YL Fan

**Comment by DaveHealy-github** [comment]
Hello

thanks for your e-mail and interest in FracPaQ.

My rule of thumb for choosing the threshold is try and put the line on the graphs just below the yellow peaks. There is no objective method that I know of. The idea is just to select the ‘significant’ peaks.

Values of 0.4 – 0.6 normally work well.

Cheers,
Dave

Prof David Healy [he/him]
School of Geosciences
Meston Walk
University of Aberdeen
Aberdeen AB24 3UE

Visiting Academic, University of Manchester

My working day may not be your working day. Please do not feel obliged to reply to this e-mail outside of your normal working hours.

Publications: https://scholar.google.com/citations?hl=en&user=ug9DnVoAAAAJ
Software: https://github.com/DaveHealy-github/
FracPaQ: https://github.com/DaveHealy-github/FracPaQ
PFS: https://github.com/DaveHealy-github/pfs
Home page: https://www.abdn.ac.uk/people/d.healy/



From: YL Fan ***@***.***>
Reply to: DaveHealy-github/FracPaQ ***@***.***>
Date: Sunday, 5 June 2022 at 10:18
To: DaveHealy-github/FracPaQ ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DaveHealy-github/FracPaQ] How do I determine if the Hough threshold is chosen correctly? (Issue #9)

CAUTION: External email. Ensure this message is from a trusted source before clicking links/attachments.


Hi All,

This program is so convenient and very helpful to me, thanks for this great tool!

I'm ashamed that I don't know much about the field of image analysis.
I felt that the User Guide was vague about determining a reasonable Hough threshold.
Could you explain it to me in detail?

Many thanks!
YL Fan

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDaveHealy-github%2FFracPaQ%2Fissues%2F9&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cc6bac058dc41440809d208da46d45c58%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637900175142207411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BacGhEnOJio7ahJy%2F5i5GgmibjbI4zmbMwb0zUYgd38%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAESJKRTACAGVNQNJU7EXFMTVNRWGLANCNFSM5X4YSWBQ&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cc6bac058dc41440809d208da46d45c58%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637900175142207411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3i6ChA89lmqQ2k29Np3I1QODssQAv1on%2FevtnDdk2Qg%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.

**Comment by fkcllll** [comment]
> Hello thanks for your e-mail and interest in FracPaQ. My rule of thumb for choosing the threshold is try and put the line on the graphs just below the yellow peaks. There is no objective method that I know of. The idea is just to select the ‘significant’ peaks. Values of 0.4 – 0.6 normally work well. Cheers, Dave Prof David Healy [he/him] School of Geosciences Meston Walk University of Aberdeen Aberdeen AB24 3UE Visiting Academic, University of Manchester My working day may not be your working day. Please do not feel obliged to reply to this e-mail outside of your normal working hours. Publications: https://scholar.google.com/citations?hl=en&user=ug9DnVoAAAAJ Software: https://github.com/DaveHealy-github/ FracPaQ: https://github.com/DaveHealy-github/FracPaQ PFS: https://github.com/DaveHealy-github/pfs Home page: https://www.abdn.ac.uk/people/d.healy/ From: YL Fan ***@***.***> Reply to: DaveHealy-github/FracPaQ ***@***.***> Date: Sunday, 5 June 2022 at 10:18 To: DaveHealy-github/FracPaQ ***@***.***> Cc: Subscribed ***@***.***> Subject: [DaveHealy-github/FracPaQ] How do I determine if the Hough threshold is chosen correctly? (Issue #9) CAUTION: External email. Ensure this message is from a trusted source before clicking links/attachments. Hi All, This program is so convenient and very helpful to me, thanks for this great tool! I'm ashamed that I don't know much about the field of image analysis. I felt that the User Guide was vague about determining a reasonable Hough threshold. Could you explain it to me in detail? Many thanks! YL Fan — Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDaveHealy-github%2FFracPaQ%2Fissues%2F9&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cc6bac058dc41440809d208da46d45c58%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637900175142207411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BacGhEnOJio7ahJy%2F5i5GgmibjbI4zmbMwb0zUYgd38%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAESJKRTACAGVNQNJU7EXFMTVNRWGLANCNFSM5X4YSWBQ&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cc6bac058dc41440809d208da46d45c58%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637900175142207411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3i6ChA89lmqQ2k29Np3I1QODssQAv1on%2FevtnDdk2Qg%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> The University of Aberdeen is a charity registered in Scotland, No SC013683. Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.

**Comment by fkcllll** [comment]
Thank you for all your assistance.There are many yellow columns in the graph, which together with the orange columns below form a 'ridge line'. Do you mean to place the straight line under all the Yellow columns or make the line just under all the 'valleys'?

**Comment by DaveHealy-github** [comment]
Again, it’s ‘Trial & Error’ I’m afraid.

Try beneath the yellow, and consider the output fracture trace map...

Cheers,
Dave

Prof David Healy [he/him]
School of Geosciences
Meston Walk
University of Aberdeen
Aberdeen AB24 3UE

Visiting Academic, University of Manchester

My working day may not be your working day. Please do not feel obliged to reply to this e-mail outside of your normal working hours.

Publications: https://scholar.google.com/citations?hl=en&user=ug9DnVoAAAAJ
Twitter: @listen2mcr @fracpaq
Software: https://github.com/DaveHealy-github/
FracPaQ: https://github.com/DaveHealy-github/FracPaQ
PFS: https://github.com/DaveHealy-github/pfs
Home page: https://www.abdn.ac.uk/people/d.healy/



From: YL Fan ***@***.***>
Reply to: DaveHealy-github/FracPaQ ***@***.***>
Date: Friday, 10 June 2022 at 13:47
To: DaveHealy-github/FracPaQ ***@***.***>
Cc: "Healy, David" ***@***.***>, Comment ***@***.***>
Subject: Re: [DaveHealy-github/FracPaQ] How do I determine if the Hough threshold is chosen correctly? (Issue #9)

CAUTION: External email. Ensure this message is from a trusted source before clicking links/attachments.


Thank you for all your assistance.There are many yellow columns in the graph, which together with the orange columns below form a 'ridge line'. Do you mean to place the straight line under all the Yellow columns or make the line just under all the 'valleys'?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDaveHealy-github%2FFracPaQ%2Fissues%2F9%23issuecomment-1152323305&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cd71f04b48f3e4ce7400408da4adf6f9d%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637904620757405193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uIcEkF92p1alAi%2Flor3A0S%2Ba4Vk3cQo7gHR6r6fEmOw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAESJKRWELRJGOAWCBMW2LJ3VOM2PNANCNFSM5X4YSWBQ&data=05%7C01%7Cd.healy%40abdn.ac.uk%7Cd71f04b48f3e4ce7400408da4adf6f9d%7C8c2b19ad5f9c49d490773ec3cfc52b3f%7C0%7C0%7C637904620757405193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7JYtzuHvXq%2Bbtg4I%2FoIeLQAiqksPkf7MuN5SzKzTkVY%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>


The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.
